version: '3.8'

services:
  mintlify:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: mintlify dev --host 0.0.0.0 