name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build MCP server
      run: npm run build
    
    - name: Build landing page
      working-directory: ./landing
      run: |
        npm install
        npm run build
    
    - name: Build documentation
      working-directory: ./docs
      run: |
        npm install -g mintlify
        mintlify build
    
    - name: Prepare deployment
      run: |
        mkdir -p dist-site
        cp -r landing/dist/* dist-site/
        mkdir -p dist-site/docs
        cp -r docs/.mintlify/build/* dist-site/docs/
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist-site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4