name: Release

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    
    - run: npm ci
    
    - run: npm run build
    
    - run: npm test
    
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  publish-dxt:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
    - uses: actions/checkout@v4
    
    - name: Notify DXT Registry
      run: |
        curl -X POST https://dxt.anthropic.com/api/packages \
          -H "Authorization: Bearer ${{ secrets.DXT_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "gemini-cli-mcp-for-claude",
            "version": "${{ github.event.release.tag_name }}",
            "repository": "https://github.com/gunta/gemini-cli-mcp-for-claude-code"
          }'